[package]
name = "roy-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
roy-common = { path = "../roy-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { version = "*" }

[[bin]]
name = "roy"
path = "src/main.rs"
